### ISSUE TITLE
Error with --vaf Parameter

### ISSUE THREAD

**Issue by linsindian** [KolmogorovLab/minda#1]
Hello, I encountered an error related to the --vaf parameter while using Minda.
I would like to inquire about how to configure it. 
I've tried values such as 0.1, 0.5, and 0, but they all result in the following error.
 ``` 
 [2024-03-26 02:17:27] INFO: DECOMPOSING LP_PAO RECORDS... 
[2024-03-26 02:17:27] INFO: Original number of records: 130 
[2024-03-26 02:17:27] INFO: Number of after filtering by FILTER column: 130 
[2024-03-26 02:17:28] INFO: Number of unique indices: 39 
[2024-03-26 02:17:28] INFO: 38 paired records and 92 unpaired records found... 
[2024-03-26 02:17:28] INFO: Number of paired records paired by ALT column: 19 19 
[2024-03-26 02:17:28] INFO: Number of unpaired records paired by MATE_ID: 0 0 
[2024-03-26 02:17:28] INFO: Number of unpaired records paired by INFO column: 92 92 
[2024-03-26 02:17:28] INFO: Number of singleton records dropped: 0 
[2024-03-26 02:17:29] INFO: Number of decomposed records after pairing: 111 111 
[2024-03-26 02:17:29] INFO: Number of records after VAF filtering: 0 0 
[2024-03-26 02:17:29] INFO: Total number of decomposed records: 0 0 
[2024-03-26 02:17:29] INFO: DECOMPOSING truthset RECORDS... 
[2024-03-26 02:17:29] INFO: Original number of records: 49 
[2024-03-26 02:17:29] INFO: Number of after filtering by FILTER column: 49 
[2024-03-26 02:17:29] INFO: Number of unique indices: 1 
[2024-03-26 02:17:29] INFO: No paired records found... 
[2024-03-26 02:17:29] INFO: Number of paired records paired by ALT column: 0 0 
[2024-03-26 02:17:29] INFO: Number of unpaired records paired by MATE_ID: 0 0 
[2024-03-26 02:17:29] INFO: Number of unpaired records paired by INFO column: 45 45 
[2024-03-26 02:17:29] INFO: Number of singleton records dropped: 4 
[2024-03-26 02:17:29] INFO: Number of decomposed records after pairing: 45 45 
[2024-03-26 02:17:29] INFO: Number of records after VAF filtering: 0 0 
[2024-03-26 02:17:29] INFO: Total number of decomposed records: 0 0 
Traceback (most recent call last):
  File "./minda/minda.py", line 26, in <module>
    main()
  File "./minda/minda.py", line 22, in main
    sys.exit(main())
  File "./minda/minda/main.py", line 211, in main
    args.func(args)
  File "./minda/minda/main.py", line 141, in run
    results = get_results(decomposed_dfs_list, support_df, caller_names, args.out_dir, args.sample_name, max_len, args.tolerance, args.vaf,args.command, args)
  File "./minda/minda/stats.py", line 91, in get_results
    stats_dfs = _get_stats_df(tp_df, fn_df, fp_df, paired_df, base_df, caller_name, max_len, out_dir, sample_name)
  File "./minda/minda/stats.py", line 53, in _get_stats_df
    precision = tp/(tp+fp)
ZeroDivisionError: division by zero
``` 
Program operates normally when the --vaf parameter is unspecified. 
Benchmark used is from [COLO829 new benchmark](https://www.medrxiv.org/content/10.1101/2024.03.15.24304369v1) and the VCF for comparison is generated by Severus. 

Best, 
Sin-Dian

**Comment by asherbryant** [comment]
Hello Sin-Dian,
The INFO field must have a VAF value, which requires preprocessing the VCF. Since calculating the VAF is very specific for each caller, this feature has not been incorporated into Minda. However, we will share a Python script we used for the Severus paper shortly.

**Comment by asherbryant** [comment]
Hello Sin-Dian,

Thank you for reporting this and sorry for the omission in the readme about using `--vaf.` To use `--vaf`, the VCFs must be preprocessed so that the INFO field has `VAF=<float>`. Since adding VAF is specific to each caller, this has not been incorporated into Minda. But the Python script to modify a Severus VCF has been added to [scripts](https://github.com/KolmogorovLab/minda/tree/main/scripts).

As far as the new benchmark, I have modified its quirky elements and add `VAF=<float>`. The BND records have been modified because In the original VCF Minda interpets BNDs as singletons (I also removed all double quotation marks from INFO though this doesn't affect Minda when running `truthset`). You can find that VCF in [data](https://github.com/KolmogorovLab/minda/tree/main/data) (and that VAF [scripts](https://github.com/KolmogorovLab/minda/tree/main/scripts) is also in scripts, if you're curious).

Best,
Asher
